// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQlSKVdWyM8KztX5GzGfd7KFevhwFLzk',
    appId: '1:543633740251:web:08461dafb6110c091497fe',
    messagingSenderId: '543633740251',
    projectId: 'messagex-b2cfd',
    authDomain: 'messagex-b2cfd.firebaseapp.com',
    storageBucket: 'messagex-b2cfd.appspot.com',
    measurementId: 'G-YH0HTHBK0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWm_f10b7ULvnIelGEpK2hxHc-TZy_GFw',
    appId: '1:543633740251:android:1e541d1b034544861497fe',
    messagingSenderId: '543633740251',
    projectId: 'messagex-b2cfd',
    storageBucket: 'messagex-b2cfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwWfnijJaQpiuTQPeKq7pUJqKXZoZ4rzw',
    appId: '1:543633740251:ios:91d5b485b2c8f8141497fe',
    messagingSenderId: '543633740251',
    projectId: 'messagex-b2cfd',
    storageBucket: 'messagex-b2cfd.appspot.com',
    iosClientId: '543633740251-rhqq1lj30gfjo76mmtv970utqiuc1scc.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwWfnijJaQpiuTQPeKq7pUJqKXZoZ4rzw',
    appId: '1:543633740251:ios:50fba2f8e478fac31497fe',
    messagingSenderId: '543633740251',
    projectId: 'messagex-b2cfd',
    storageBucket: 'messagex-b2cfd.appspot.com',
    iosClientId: '543633740251-9og927mkrlrcbg8urt2de86h919sfboe.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagex.RunnerTests',
  );
}
